# Generated by Django 4.0.4 on 2022-08-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0004_tutor_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='imagen',
            field=models.ImageField(null=True, upload_to='docentes'),
        ),
    ]
